name: Update @tscircuit/core

on:
  workflow_dispatch:

jobs:
  update-core:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        
      - name: Update @tscircuit/core
        run: bun update --latest @tscircuit/core
        
      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code || echo "changes=true" >> $GITHUB_OUTPUT
          
      - name: Create Pull Request
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: update @tscircuit/core to latest version"
          title: "chore: update @tscircuit/core to latest version"
          body: |
            Automated update of @tscircuit/core to the latest version.
            
            This PR was created automatically by the update-tscircuit-core GitHub workflow.
          branch: update-tscircuit-core
          base: main
          token: ${{ secrets.TSCIRCUIT_BOT_GITHUB_TOKEN }}
          committer: tscircuit-bot <bot@tscircuit.com>
          author: tscircuit-bot <bot@tscircuit.com>